import type { NextPage } from 'next'
import Head from 'next/head'
import NavBar from '../components/NavBar'
import Todo from '../components/Todo'
import { minifyRecords, table } from './api/utils/Airtable'
import React, { useEffect, useContext } from 'react'
import { TodosContext } from '../contexts/TodosContext'
import { useAuth0 } from '@auth0/auth0-react';
import TodoForm from '../components/TodoForm'

type HomeProps = {
  initialTodos: TodoObject[]
}

const Home: NextPage<HomeProps> = (props) => {
  const { initialTodos } = props
  const { todos, setTodos } = useContext(TodosContext)
  const {
    isLoading,
    isAuthenticated,
    error,
    user,
    loginWithRedirect,
    logout,
  } = useAuth0();

  useEffect(() => {
    setTodos(initialTodos)
  }, [])

    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar user={user} logout={logout} login={loginWithRedirect}/>
        <main>
          {
            isLoading? 
              <div>Loading...</div>
            : error? 
                <div>Oops... {error.message}</div>
              : isAuthenticated? 
                <>
                  <h1 className="text-2xl text-center mb-4">My Todos</h1>
                  <TodoForm />
                  <ul>
                    {todos &&
                      todos.map((todo) => <Todo key={todo.id} todo={todo} />)
                    }
                  </ul>
                </>
                : <></>    
          }
            
        </main>  
      </div>
    )
}

export async function getServerSideProps() {

  try{
    const todos = await table.select({}).firstPage()
    return {
      props: {
        initialTodos: minifyRecords(todos)
      }
    }
  }catch(err){
    console.error(err);
    return {
      props: {
        err: "Something went wrong!"
      }
    }
  }
  
}

export default Home
